# Generated by Django 6.0.7 on 2026-07-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_failed_attempts_userprofile_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_required',
            field=models.BooleanField(default=False),
        ),
    ]
