# Generated by Django 6.0.7 on 2026-07-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_password_reset_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='failed_login_attempts',
            new_name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lock_reason',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password_reset_required',
        ),
    ]
