# Generated by Django 6.0.7 on 2026-07-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_failed_login_attempts_userprofile_failed_attempts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='failed_attempts',
            new_name='failed_login_attempts',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lock_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_required',
            field=models.BooleanField(default=False),
        ),
    ]
